export const HTTP_RESOURCES = {
    users:'users',
    mentors:'mentors'
    // qrCodes: 'qrCodes',
    // inventory: 'inventory',
    // userPoints: 'userPoints',
    // inventoryEvents: 'inventoryEvents',
    // clientPhysicalDocs: 'clientPhysicalDocs',
    // personalToDoList: 'personalToDoList',
    // subTasksOftaskClientAssociations: 'subTasks/taskClientAssociations' ,
    // taskClientAssociation: {
    //     metadataOverride:"taskClientAssociations/:taskClientAssocId/metadataOverride",
    //     tasks: 'taskClientAssociations',
    //     taskAutomation: 'taskClientAssociations/generate',
    //     task: 'taskClientAssociations/:taskClientAssocId',
    //     taskSnooze: 'taskClientAssociations/:taskClientAssocId/snooze',
    //     subTaskList: 'taskClientAssociations/:taskClientAssocId/subTasks',
    //     subTask: 'taskClientAssociations/:taskClientAssocId/subTasks/:subTaskId',
    //     search: {
    //         tasks: 'search/taskClientAssociations'
    //     },
    //     billedTasks: 'taskClientAssociations/billed/tasks',
    //     completedToPrimary: 'taskClientAssociations/completed/moveBackToPrimary',
    //     snoozedToPrimary: 'taskClientAssociations/snoozed/moveBackToPrimary',
    //     unBilledTasks:'taskClientAssociations/unBilled/tasks',
    //     completeStatus: {
    //         billed: 'taskClientAssociations/:taskClientAssocId/completeStatus/billed',
    //         nonbilled:'taskClientAssociations/:taskClientAssocId/completeStatus/nonbillable'
    //     },
    //     bulkTasks:"taskClientAssociations/bulkTaskClientAssociation",
    //     priorityTasks:"priorityTasks",
    //     deletPriorityTask:"priorityTasks/:taskId/:email"
    // },
    // reports: {
    //     invoiceReport:'reports/invoiceReport',
    //     taskinvoiceReport:'reports/taskinvoiceReport',
    //     completedTaskReport: 'reports/completed',
    //     primaryTaskReport: 'reports/primaryTaskList',
    //     userEvaluationReport:'reports/userEvaluationReport',
    //     workLogReports:'reports/workLogReports'
    // },
    // clients: 'clients',
    // clientFiles: 'clients/:clientId/files',
    // tasks: 'tasks',
    // subTasks: 'subTasks',
    // subTaskForTaskClient: 'subTask/taskClientAssociation',
    // snoozedTasks: 'snoozedTasks',
    // subTaskSearch: 'subTaskSearch',
    // searchSubTasks: "searchSubTasks",
    // invoices:"invoices",
    // taskinvoices:"taskinvoices",
    // getHsnSacCodeDetails:"hsnSacDetails",
    // deleteInvoice:"invoices/:invoiceId",
    // hsnSacConfig:"hsnSacConfig",
    // updateHsnSacConfig:"hsnSacConfig/:uid",
    // priorityTask:"priorityTasks",
    // audits: 'audits',
    // completedTasks: 'completedTasks',
    // moveToBilled: 'completedTasks/moveToBilled',
    // moveToNonBillable: 'completedTasks/moveToNonBillable',
    // taskAssigneeList: 'tasks/:taskId/assignees',
    // taskReviewerList: 'tasks/:taskId/reviewers',
    // taskDueDate: 'tasks/:taskId/dueDate',
    // taskStatus: 'tasks/:taskId/status',
    // taskConfiguration: 'taskConfiguration',
    // taskPeriodicity: 'taskPeriodicity',
    // newTaskPeriodicity: 'newTaskPeriodicity',
    // taskListToBeCreated: 'taskListToBeCreated',
    // taskPeriodCreationInputs: 'taskPeriodCreationInputs',
    // task: 'tasks/:taskId',
    // taskAudit: 'tasks/:taskId/audit',
    // taskAttachments: 'tasks/:taskId/attachments',
    // deleteTaskAttachment:"tasks/:sk/attachments",
    // taskMessages: 'tasks/:taskId/messages',
    // markAsRead: 'tasks/:taskId/messages/markAsRead',
    // reviewers: 'reviewers',
    // automatedTasks:'automatedTasks',
    // workLog: 'workLog',
    // orgInvoiceSettings: 'orgInvoiceSettings',
    // orgPaymentSettings: 'orgPaymentSettings',
    // workLogList:"workLogList",
    // seedData: {
    //     org: {
    //         userRoles: 'organization/userRoles',
    //         userDesignations: 'organization/userDesignationList',
    //         taskCategory: 'organization/taskCategory',
    //         taskStatusList: 'organization/taskStatusList',
    //         taskUpdateReasons: 'organization/taskUpdateReasons',
    //         taskPeriodList: 'organization/taskPeriodList',
    //         taskDocumentTypes: 'organization/taskDocumentTypes',
    //         clientTypes: 'organization/clientTypes',
    //     }
    // },
    // search: {
    //     tasks: 'search/tasks'
    // },
    // newUser: 'organization/newUser',
    // newCognitoUser: 'organization/newCognitoUser',
    // updateCognitoUser: 'organization/updateCognitoUser',
    // disableCognitoUser: 'organization/disableCognitoUser',
    // enableCognitoUser: 'organization/enableCognitoUser',
    // deleteCognitoUser: 'organization/deleteCognitoUser',
    // users: 'users',
    // taskCategoryFiles:'taskCategoryFiles',
    // orgEmail: 'organization/email',
    // notifications: 'organization/notifications',
    // acknowledgeNotifications: 'organization/notifications/acknowledge',
    // organisation: 'organisation',
    // organisationSettings: 'orgSettings',
    // clientMasterfiles:'clientMasterFiles',
    // bulkTaskCreationSummary:"bulkTaskCreationSummary",
    // leaveDetails:'leaveDetails',
    // rewardConfiguration:'rewardConfiguration',
    // userRewards:'userRewards',
    // configuredHolidays:'configuredHolidays'
}